// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgrcrlhwyxhttgfhuvbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ncmNybGh3eXhodHRnZmh1dmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1OTE3OTksImV4cCI6MjA1NjE2Nzc5OX0.j9uewX8f-ClbaRRcgXGf9KB1GuP_zHWy82VLE0C2d2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);